In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("C:/Users/hp/Downloads/nba.csv")

In [5]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [7]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='str')

In [8]:
df["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: str

In [9]:
df1=df[["Name","Salary"]]
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df["Experience"]=2

In [11]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2

In [14]:
df["Salary_after_bonus"]=df["Salary"]*1.10
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN

In [15]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0

In [16]:
df2=df.drop("Experience",axis=1)
df2

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5500000.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0

In [18]:
df3=df2.drop("Salary_after_bonus",axis=1)
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### loc and iloc in panda

In [2]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}
df=pd.DataFrame(data)
print(df)

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [3]:
df.loc[[1,3]]

    Name  Age Department  Salary
1    Bob   25         IT   50000
3  David   24         IT   52000

In [4]:
df.loc[2,"Name"]

'Charlie'

In [5]:
df.loc[2,["Name","Salary"]]

Name      Charlie
Salary      45000
Name: 2, dtype: object

In [6]:
df.loc[[1,3],["Name","Department"]]

    Name Department
1    Bob         IT
3  David         IT

In [7]:
df.loc[1:3]

      Name  Age Department  Salary
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000

In [8]:
df.loc[df["Salary"]>45000]

    Name  Age Department  Salary
1    Bob   25         IT   50000
3  David   24         IT   52000
4   Emma   26  Marketing   48000

In [10]:
df.loc[df["Salary"] > 45000, ["Name", "Salary"]]

    Name  Salary
1    Bob   50000
3  David   52000
4   Emma   48000

In [11]:
df.loc[2,"Salary"]=47000
df

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [12]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

df = pd.DataFrame(data,index=[1,2,3,4,5])



print(df)

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000
5     Emma   26  Marketing   48000

In [13]:
df.loc[1]

Name          Alice
Age              23
Department       HR
Salary        40000
Name: 1, dtype: object

In [14]:
df.iloc[1]

Name            Bob
Age              25
Department       IT
Salary        50000
Name: 2, dtype: object

In [15]:
df.loc[1:4]

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [16]:
df.iloc[1:4]

      Name  Age Department  Salary
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [17]:
df.iloc[2]

Name          Charlie
Age                22
Department    Finance
Salary          45000
Name: 3, dtype: object

In [18]:
df.iloc[[1,3]]

    Name  Age Department  Salary
2    Bob   25         IT   50000
4  David   24         IT   52000

In [19]:
df.iloc[2,[0,3]]

Name      Charlie
Salary      45000
Name: 3, dtype: object

In [20]:
df.iloc[[1,3],[0,2]]

    Name Department
2    Bob         IT
4  David         IT

In [21]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

In [23]:
df=pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [24]:
df.shape

(5, 4)

In [25]:
df.info

<bound method DataFrame.info of       Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000>

In [27]:
df.head(2)

    Name  Age Department  Salary
0  Alice   23         HR   40000
1    Bob   25         IT   50000

In [28]:
df.tail(2)

    Name  Age Department  Salary
3  David   24         IT   52000
4   Emma   26  Marketing   48000

In [29]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Age": [23, 45, 31, 22, 35, 28],
    "Salary": [40000, 80000, 50000, 30000, 90000, 60000],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance"]
}

df = pd.DataFrame(data)

# custom index
df.index = ["emp1", "emp2", "emp3", "emp4", "emp5", "emp6"]

print(df)

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp2    B   45   80000         IT
emp3    C   31   50000    Finance
emp4    D   22   30000         HR
emp5    E   35   90000         IT
emp6    F   28   60000    Finance

In [31]:
df.iloc[0:3]

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp2    B   45   80000         IT
emp3    C   31   50000    Finance

In [32]:
df.iloc[2:5,1:3]

      Age  Salary
emp3   31   50000
emp4   22   30000
emp5   35   90000

In [33]:
df.iloc[:, 0:2]

     Name  Age
emp1    A   23
emp2    B   45
emp3    C   31
emp4    D   22
emp5    E   35
emp6    F   28

In [34]:
df.loc["emp1":"emp3"]

     Name  Age  Salary Department
emp1    A   23   40000         HR
emp2    B   45   80000         IT
emp3    C   31   50000    Finance

In [35]:
df.loc["emp2":"emp5", "Name":"Salary"]

     Name  Age  Salary
emp2    B   45   80000
emp3    C   31   50000
emp4    D   22   30000
emp5    E   35   90000

In [36]:
df.loc[:,"Age":"Department"]

      Age  Salary Department
emp1   23   40000         HR
emp2   45   80000         IT
emp3   31   50000    Finance
emp4   22   30000         HR
emp5   35   90000         IT
emp6   28   60000    Finance

In [39]:
df.loc["emp3":, :]

     Name  Age  Salary Department
emp3    C   31   50000    Finance
emp4    D   22   30000         HR
emp5    E   35   90000         IT
emp6    F   28   60000    Finance

In [41]:
df.loc["emp2":"emp4","Salary"]

emp2    80000
emp3    50000
emp4    30000
Name: Salary, dtype: int64