In [32]:
import pandas as pd

In [33]:
data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 3, 8, 4, 9],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           3      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           9     Mumbai

In [34]:
df.groupby("Department")["Salary"].mean()

Department
Finance    71000.000000
HR         42500.000000
IT         62333.333333
Name: Salary, dtype: float64

In [35]:
df.groupby("Department")["Salary"].sum()

Department
Finance    142000
HR          85000
IT         187000
Name: Salary, dtype: int64

In [36]:
df.groupby("Department")["Salary"].max()

Department
Finance    72000
HR         45000
IT         65000
Name: Salary, dtype: int64

In [37]:
df.groupby("Department")["Salary"].min()

Department
Finance    70000
HR         40000
IT         60000
Name: Salary, dtype: int64

In [38]:
df.groupby("Department")["Employee"].count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [39]:
df.groupby("City")["Employee"].count()

City
Bangalore    1
Chennai      2
Kochi        3
Mumbai       1
Name: Employee, dtype: int64

In [40]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

                    mean    max    min
Department
Finance     71000.000000  72000  70000
HR          42500.000000  45000  40000
IT          62333.333333  65000  60000

In [41]:
df.groupby("Department").agg({"Salary":["mean","max"],"Experience":["min","max"]})

                  Salary        Experience
                    mean    max        min max
Department
Finance     71000.000000  72000          8   9
HR          42500.000000  45000          2   3
IT          62333.333333  65000          4   6

### Named Aggrigate

In [42]:
df.groupby("Department").agg(Average_Salary=("Salary","mean"),
                             Maximum_Salary=("Salary","max"),
                             Maximum_Experience=("Experience","max")
                             ,Minimum_Experience=("Experience","min"))

,Average_Salary,Maximum_Salary,Maximum_Experience,Minimum_Experience
Department,,,,
Finance,71000.000000,72000,9,8
HR,42500.000000,45000,3,2
IT,62333.333333,65000,6,4

In [43]:
df.groupby("Department").agg(Average_Salary=("Salary","mean"),
                             Maximum_Salary=("Salary","max"),
                             Maximum_Experience=("Employee","count"))

            Average_Salary  Maximum_Salary  Maximum_Experience
Department
Finance       71000.000000           72000                   2
HR            42500.000000           45000                   2
IT            62333.333333           65000                   3

In [44]:
even = lambda i : i% 2== 0
for i in range(0,10):
    if even(i):
        print(i)

0
2
4
6
8

In [45]:
import pandas as pd

df = pd.DataFrame({
    "Numbers": [1, 2, 3, 4]
})

df["Square"] = df["Numbers"].apply(lambda x: x**2)
print(df)

   Numbers  Square
0        1       1
1        2       4
2        3       9
3        4      16

In [54]:
import pandas as pd
data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 2, 8, 4, 8],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df1 = pd.DataFrame(data)
df1

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           2      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           8     Mumbai

In [56]:
df1["Dept_Avg_Salary"] = df1.groupby("Department")["Salary"].transform("mean")
df1

  Department Employee  Salary  Experience       City  Dept_Avg_Salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           2      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           8     Mumbai     71000.000000

In [58]:
df1["Salary_Diff"] = df1["Salary"] - df1["Dept_Avg_Salary"]
df1

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,Salary_Diff
0,HR,A,40000,2,Bangalore,42500.000000,-2500.000000
1,IT,B,60000,5,Chennai,62333.333333,-2333.333333
2,IT,C,65000,6,Kochi,62333.333333,2666.666667
3,HR,D,45000,2,Kochi,42500.000000,2500.000000
4,Finance,E,70000,8,Chennai,71000.000000,-1000.000000
5,IT,F,62000,4,Kochi,62333.333333,-333.333333
6,Finance,G,72000,8,Mumbai,71000.000000,1000.000000

In [61]:
df1["Salary_Percent"]=df1["Salary"]/df1.groupby("Department")["Salary"].transform("sum")

In [62]:
df1

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,Salary_Diff,Salary_Percent
0,HR,A,40000,2,Bangalore,42500.000000,-2500.000000,0.470588
1,IT,B,60000,5,Chennai,62333.333333,-2333.333333,0.320856
2,IT,C,65000,6,Kochi,62333.333333,2666.666667,0.347594
3,HR,D,45000,2,Kochi,42500.000000,2500.000000,0.529412
4,Finance,E,70000,8,Chennai,71000.000000,-1000.000000,0.492958
5,IT,F,62000,4,Kochi,62333.333333,-333.333333,0.331551
6,Finance,G,72000,8,Mumbai,71000.000000,1000.000000,0.507042

In [63]:
df1["Dpt_avg_Salary"]=df1.groupby("Department")["Salary"].transform("mean")

In [64]:
df1

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,Salary_Diff,Salary_Percent,Dpt_avg_Salary
0,HR,A,40000,2,Bangalore,42500.000000,-2500.000000,0.470588,42500.000000
1,IT,B,60000,5,Chennai,62333.333333,-2333.333333,0.320856,62333.333333
2,IT,C,65000,6,Kochi,62333.333333,2666.666667,0.347594,62333.333333
3,HR,D,45000,2,Kochi,42500.000000,2500.000000,0.529412,42500.000000
4,Finance,E,70000,8,Chennai,71000.000000,-1000.000000,0.492958,71000.000000
5,IT,F,62000,4,Kochi,62333.333333,-333.333333,0.331551,62333.333333
6,Finance,G,72000,8,Mumbai,71000.000000,1000.000000,0.507042,71000.000000

In [69]:
df1["count_emp_Dept"] =df1.groupby("Department")["Employee"].transform("count")

In [70]:
df1

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,Salary_Diff,Salary_Percent,Dpt_avg_Salary,count_emp_Dept
0,HR,A,40000,2,Bangalore,42500.000000,-2500.000000,0.470588,42500.000000,2
1,IT,B,60000,5,Chennai,62333.333333,-2333.333333,0.320856,62333.333333,3
2,IT,C,65000,6,Kochi,62333.333333,2666.666667,0.347594,62333.333333,3
3,HR,D,45000,2,Kochi,42500.000000,2500.000000,0.529412,42500.000000,2
4,Finance,E,70000,8,Chennai,71000.000000,-1000.000000,0.492958,71000.000000,2
5,IT,F,62000,4,Kochi,62333.333333,-333.333333,0.331551,62333.333333,3
6,Finance,G,72000,8,Mumbai,71000.000000,1000.000000,0.507042,71000.000000,2

In [71]:
df1["max_Salary_per_Dpt"]= df1.groupby("Department")["Salary"].transform("max")
df1

,Department,Employee,Salary,Experience,City,Dept_Avg_Salary,Salary_Diff,Salary_Percent,Dpt_avg_Salary,count_emp_Dept,max_Salary_per_Dpt
0,HR,A,40000,2,Bangalore,42500.000000,-2500.000000,0.470588,42500.000000,2,45000
1,IT,B,60000,5,Chennai,62333.333333,-2333.333333,0.320856,62333.333333,3,65000
2,IT,C,65000,6,Kochi,62333.333333,2666.666667,0.347594,62333.333333,3,65000
3,HR,D,45000,2,Kochi,42500.000000,2500.000000,0.529412,42500.000000,2,45000
4,Finance,E,70000,8,Chennai,71000.000000,-1000.000000,0.492958,71000.000000,2,72000
5,IT,F,62000,4,Kochi,62333.333333,-333.333333,0.331551,62333.333333,3,65000
6,Finance,G,72000,8,Mumbai,71000.000000,1000.000000,0.507042,71000.000000,2,72000

In [81]:
df1["Dpt_avg_Salary"].max()

np.float64(71000.0)